// <auto-generated />
using System;
using Kmd.Logic.Identity.Examples.DatesApi.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Kmd.Logic.Identity.Examples.DatesApi.Migrations
{
    [DbContext(typeof(DatesDbContext))]
    partial class DatesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("Kmd.Logic.Identity.Examples.DatesApi.Domain.DateDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("Date");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("DateDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
